#cloud-config
hostname: {{NAME}}
fqdn: {{NAME}}.local
users:
  - name: node
    groups: [sudo]
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    ssh_authorized_keys:
      - "{{PUBLIC_KEY}}"
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - sh -c 'curl -fsSL https://tailscale.com/install.sh | sh'
  - tailscale up --auth-key={{TS_AUTH_KEY}} --hostname={{NAME}}
  - tailscale set --ssh
